SECTION "Maps", ROM0

EXPORT Map1

MACRO ROW_WALLS
    REPT MAP_WIDTH
        DB MT_WALL
    ENDR
ENDM

MACRO ROW_EMPTY
    DB MT_WALL
    REPT MAP_WIDTH - 2
        DB MT_FLOOR
    ENDR
    DB MT_WALL
ENDM

MACRO ROW_EXIT
    DB MT_WALL
    REPT MAP_WIDTH - 3
        DB MT_FLOOR
    ENDR
    DB MT_EXIT
    DB MT_WALL
ENDM

; Row with a horizontal wall leaving a gap on the left
MACRO ROW_BAR_LEFT
    DB MT_WALL
    DB MT_FLOOR
    REPT MAP_WIDTH - 3
        DB MT_WALL
    ENDR
    DB MT_WALL
ENDM

; Row with a horizontal wall leaving a gap on the right
MACRO ROW_BAR_RIGHT
    DB MT_WALL
    REPT MAP_WIDTH - 3
        DB MT_WALL
    ENDR
    DB MT_FLOOR
    DB MT_WALL
ENDM

; Bottom row with the exit in the bottom-right corner
MACRO ROW_EXIT_CORNER
    DB MT_WALL
    REPT MAP_WIDTH - 2
        DB MT_FLOOR
    ENDR
    DB MT_EXIT
ENDM

; ----- Map 1 -----
; Maze layout inspired by the provided black square image.  Each row is
; explicitly defined using map tile constants.  The player starts at
; coordinates (1,1) and the exit is located near the bottom right.
Map1:
    ; row 0
    DB MT_WALL,MT_FLOOR,MT_WALL,MT_WALL,MT_WALL,MT_FLOOR,MT_WALL,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_WALL,MT_WALL,MT_WALL,MT_FLOOR,MT_WALL,MT_FLOOR,MT_WALL
    ; row 1
    DB MT_WALL,MT_FLOOR,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_FLOOR,MT_WALL
    ; row 2
    DB MT_WALL,MT_FLOOR,MT_WALL,MT_FLOOR,MT_FLOOR,MT_WALL,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_FLOOR,MT_WALL
    ; row 3
    DB MT_WALL,MT_FLOOR,MT_WALL,MT_FLOOR,MT_WALL,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_WALL,MT_WALL,MT_WALL,MT_FLOOR,MT_WALL
    ; row 4
    DB MT_WALL,MT_FLOOR,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_FLOOR,MT_WALL
    ; row 5
    DB MT_WALL,MT_FLOOR,MT_WALL,MT_WALL,MT_FLOOR,MT_FLOOR,MT_WALL,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_WALL,MT_WALL,MT_FLOOR,MT_FLOOR,MT_WALL,MT_FLOOR,MT_WALL
    ; row 6
    DB MT_WALL,MT_FLOOR,MT_WALL,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_WALL,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_WALL,MT_WALL,MT_FLOOR,MT_FLOOR,MT_WALL,MT_FLOOR,MT_WALL
    ; row 7
    DB MT_WALL,MT_FLOOR,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_FLOOR,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_FLOOR,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_FLOOR,MT_WALL
    ; row 8
    DB MT_WALL,MT_FLOOR,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_FLOOR,MT_FLOOR,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_FLOOR,MT_WALL
    ; row 9
    DB MT_WALL,MT_FLOOR,MT_WALL,MT_FLOOR,MT_WALL,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_FLOOR,MT_WALL
    ; row 10
    DB MT_WALL,MT_FLOOR,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_FLOOR,MT_FLOOR,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_FLOOR,MT_WALL
    ; row 11
    DB MT_WALL,MT_FLOOR,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_WALL,MT_WALL,MT_WALL,MT_WALL,MT_FLOOR,MT_WALL
    ; row 12
    DB MT_WALL,MT_FLOOR,MT_WALL,MT_WALL,MT_WALL,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_WALL,MT_FLOOR,MT_FLOOR,MT_WALL,MT_FLOOR,MT_WALL
    ; row 13
    DB MT_WALL,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_WALL
    ; row 14
    DB MT_WALL,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_WALL
    ; row 15
    DB MT_WALL,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_WALL
    ; row 16
    DB MT_WALL,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_WALL
    ; row 17
    DB MT_WALL,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_FLOOR,MT_EXIT,MT_WALL
