; Constants.asm
DEF rLCDC = $FF40
DEF rSCX  = $FF43
DEF rSCY  = $FF42
DEF rJOYP = $FF00

; Joypad bits and select mask
DEF JOY_RIGHT      = $01
DEF JOY_LEFT       = $02
DEF JOY_UP         = $04
DEF JOY_DOWN       = $08
DEF JOY_SELECT_DPAD = $20
DEF MAP_WIDTH  = 20
DEF MAP_HEIGHT = 18

DEF MT_FLOOR = $00
DEF MT_WALL  = $01
DEF MT_EXIT  = $02
DEF MT_PLAYER = $03
DEF TILE_Y = $04
DEF TILE_O = $05
DEF TILE_U = $06
DEF TILE_W = $07
DEF TILE_I = $08
DEF TILE_N = $09
; UI tiles for the win window
DEF TILE_UI_GREY = $0A
DEF TILE_UI_HOR  = $0B
DEF TILE_UI_VERT = $0C
DEF TILE_UI_TL   = $0D
DEF TILE_UI_TR   = $0E
DEF TILE_UI_BL   = $0F
DEF TILE_UI_BR   = $10

; Window position registers
DEF rWY  = $FF4A
DEF rWX  = $FF4B
DEF PLAYER_MOVE_DELAY = 8

; Sound registers
DEF rNR52 = $FF26
DEF rNR51 = $FF25
DEF rNR50 = $FF24
DEF rNR21 = $FF16
DEF rNR22 = $FF17
DEF rNR23 = $FF18
DEF rNR24 = $FF19
